serverIp = ""
serverPort = 25565
viewDistance = 10
simulationDistance = 10
worldDir = path("world")
maxPlayers = 20
onlineMode = true
seed = null
motd = "My uno-dos-cinco server"
terrainType = terrain("default")
autosavePeriod = 5 * 60 * 20
